name: catat_pengeluaran
description: "A Flutter project to track expenses."
publish_to: 'none'  # Hapus jika ingin dipublikasikan di pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^3.0.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.10.0
  calendar_appbar: ^0.0.6
  provider: ^6.1.2
  intl: ^0.17.0
  http: ^0.13.6 # Versi terbaru yang stabil untuk http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
